export const projects = [
  {
    title: 'Project Icarus',
    description: "Using HTML, CSS, Javascript and Bootstrap - The icarus project is a personal project. The concept portrays a fictional story created by me not yet released, but which already has authorship guaranteed and a website developed.",
      image: '/images/1.png',
      tags: ['HTML5', 'CSS3', 'Javascript', 'Bootstrap'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'School Manager CCO',
    description:"lorem",
    image: '/images/2.png',
    tags: ['Java', 'MySQL', 'JFrame', 'Xamp'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Flappy Bird',
    description: "lorem",
      image: '/images/3.jpg',
      tags: ['Java'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Thiago H. Portfolio',
    description: "lorem",
    image: '/images/4.jpg',
    tags: ['JavaScript', 'Next.JS', 'ReactJS'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Robotic for everyone',
    description: "lorem",
    image: '/images/5.png',
    tags: ['HTML', 'CSS', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'Market Manager',
    description: "lorem",
    image: '/images/6.png',
    tags: ['Java', 'MySql'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey', },
  { year: 2017, text: 'Worked as a freelance frontEnd developer', },
  { year: 2020, text: 'Return my studies with Java; Spring and Angular', },
  { year: 2020.2, text: 'Make projects with these technologies to my github and i learning SCRUM', },
  { year: 2021, text: 'Started on my interprise as a java developer intern', },
  { year: 2021.2, text: 'I became a junior software engineer acting as a Scrum master analyst and fullstack java developer', },
  { year: 2022, text: 'Im become a junior developer and shared my projects with the world', },
];